config {
    type: "table",
    schema: dataform.projectConfig.vars.product_catalog_dataset,
    description: "the base daily category list table",
    tags: ["product"]
}

SELECT
  *
FROM
  ${self()}
GROUP BY
  1,
  2

pre_operations {
  LOAD DATA OVERWRITE
    ${self()} ( code_value STRING,
      code_param STRING )
  FROM FILES ( format = 'CSV',
      skip_leading_rows=1,
      uris = ['gs://kkday-retail-ai-poc-data/D/code/*.csv'] )
}
